---
title: "Final EGRET v1 Banovich application - Data Analysis"
author: "Deborah Weighill"
date: "July 28, 2020"
output:
  html_notebook:
    toc: true
    theme: cosmo
    df_print: paged
---

# Overview
Here we do some analysis on the banovich results for the "application". We start from the "master difference table" that we created.



# Load libraries
```{r}
library(dplyr)
library(preprocessCore)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(jcolors)
library(ALPACA)
library(gridExtra)
library(grid)
library(gridExtra)
pallet <- c(    "#FFBF00",  "#870E75"  ,  "#0BB19F" )
```

# load differences table differences table

```{r}
load("../outputs/diff_table_with_gwas_banovich_allModels_smart1_07042020.RData")
```

# Load gwas
```{r}

# load gene annotation to assign gene id to gene name
nameGeneMap <- read.table("../../final_egret_v1/annotation/geneID_name_map.txt", header = FALSE)
colnames(nameGeneMap) <- c("gene","name")

RA <- read.table("../gwas/RA_gwas_parsed.txt", header = FALSE,  sep = "\t")
colnames(RA) <- c("RAtrait","name")
RA$gene <- nameGeneMap$gene[match(RA$name, nameGeneMap$name)]

CD <- read.table("../gwas/CD_gwas_parsed.txt", header = FALSE,  sep = "\t")
colnames(CD) <- c("CDtrait","name")
CD$gene <- nameGeneMap$gene[match(CD$name, nameGeneMap$name)]

CAD <- read.table("../gwas/CAD_gwas_parsed.txt", header = FALSE,  sep = "\t")
colnames(CAD) <- c("CADtrait","name")
CAD$gene <- nameGeneMap$gene[match(CAD$name, nameGeneMap$name)]

BMI <- read.table("../gwas/BMI_gwas_parsed.txt", header = FALSE,  sep = "\t")
colnames(BMI) <- c("BMItrait","name")
BMI$gene <- nameGeneMap$gene[match(BMI$name, nameGeneMap$name)]

MS <- read.table("../gwas/MS_gwas_parsed.txt", header = FALSE,  sep = "\t")
colnames(MS) <- c("MStrait","name")
MS$gene <- nameGeneMap$gene[match(MS$name, nameGeneMap$name)]

MI <- read.table("../gwas/MI_gwas_parsed.txt", header = FALSE,  sep = "\t")
colnames(MI) <- c("MItrait","name")
MI$gene <- nameGeneMap$gene[match(MI$name, nameGeneMap$name)]
```


```{r}
load("../outputs/tf_diff_degree_table_banovich_smart1_07042020.RData")
load("../outputs/gene_diff_degree_table_banovich_smart1_7042020.RData")
```


plot distributions

```{r}
load("../outputs/tf_diff_degree_table_banovich_smart1_07042020.RData")
drops <- c("LCL_panda","iPSC_panda","iPSC-CM_panda")
tf_degrees <- tf_degrees[ , !(colnames(tf_degrees) %in% drops)]

tf_degrees_scaled2_lcl <- as.data.frame(t(scale(t(as.data.frame(scale(tf_degrees[,c(2:120)]), center = TRUE, scale = TRUE)))))
tf_degrees_scaled2_lcl <- cbind(tf_degrees[,c(1)], tf_degrees_scaled2_lcl)
colnames(tf_degrees_scaled2_lcl)[1] <-"tf"

tf_degrees_scaled2_iPSC <- as.data.frame(t(scale(t(as.data.frame(scale(tf_degrees[,c(121:239)]), center = TRUE, scale = TRUE)))))
tf_degrees_scaled2_iPSC <- cbind(tf_degrees[,c(1)], tf_degrees_scaled2_iPSC)
colnames(tf_degrees_scaled2_iPSC)[1] <-"tf"

tf_degrees_scaled2_iPSCCM <- as.data.frame(t(scale(t(as.data.frame(scale(tf_degrees[,c(240:358)]), center = TRUE, scale = TRUE)))))
tf_degrees_scaled2_iPSCCM <- cbind(tf_degrees[,c(1)], tf_degrees_scaled2_iPSCCM)#, tf_degrees_hard_thresh[,c(359:364)])
colnames(tf_degrees_scaled2_iPSCCM)[1] <-"tf"

tf_degrees_scaled2 <-  merge(tf_degrees_scaled2_lcl,tf_degrees_scaled2_iPSC, by.x = c(1), by.y = c(1), all = FALSE)
tf_degrees_scaled2 <-  merge(tf_degrees_scaled2,tf_degrees_scaled2_iPSCCM, by.x = c(1), by.y = c(1), all = FALSE)
tf_degrees_scaled2 <- cbind(tf_degrees_scaled2,tf_degrees[,c(359:364)])


#tf_degrees_hard_thresh_qq <- normalize.quantiles(as.matrix(tf_degrees_hard_thresh[,c(2:358)]))
#tf_degrees_hard_thresh_qq <- cbind(tf_degrees[,c(1)], tf_degrees_hard_thresh_qq, tf_degrees[,c(359:360)])
#colnames(tf_degrees_hard_thresh_qq)[1] <-"tf"

tf_degree_lcl <- melt(tf_degrees_scaled2_lcl, id.vars = c("tf"))
tf_degree_lcl$tissue <- "LCL"
tf_degree_iPSC <- melt(tf_degrees_scaled2_iPSC, id.vars = c("tf"))
tf_degree_iPSC$tissue <- "iPSC"
tf_degree_iPSC_CM <- melt(tf_degrees_scaled2_iPSCCM, id.vars = c("tf"))
tf_degree_iPSC_CM$tissue <- "iPSC-CM"
tf_degrees_melted <- data.frame(rbind(tf_degree_lcl,tf_degree_iPSC,tf_degree_iPSC_CM), stringsAsFactors = FALSE)
colnames(tf_degrees_melted) <- c("tf","individual","diff_out_degree","Tissue")

ggplot(tf_degrees_melted, aes(x=Tissue, y=diff_out_degree, fill=Tissue, col = Tissue)) + geom_violin() + theme_bw() + scale_fill_manual(values=pallet) + scale_color_manual(values=pallet) + labs(title="Distribution of TF Disruption Scores", x ="Cell type", y = "TF Disruption Score") + theme(legend.position="none")

ggplot(tf_degrees_melted, aes(x=diff_out_degree,  color=as.factor(Tissue))) + geom_density() + theme_bw() + scale_color_manual(values=pallet) +labs(title=NULL, x ="Scaled TF disruption score", y = "Frequency")

ggplot(tf_degrees_melted, aes(x=diff_out_degree,  color=Tissue, fill = Tissue)) + geom_density(alpha = 0.1) + theme_bw() + scale_color_manual(values=pallet) + scale_fill_manual(values=pallet) +labs(title=NULL, x ="Scaled TF disruption score", y = "Frequency") 



```



# Enrichment tests

## Hard threshold TF disruption scores

CAD
```{r}
tf_data <- tf_degrees_scaled2
d = 3
individuals <- c(2:358)
CAD_enrich <- sapply(individuals, FUN = function(i){
  high_diff_gwas <- length(which((tf_data[,i] >d) & (tf_data$GWAS_CAD_tf == 1)))
  low_diff_gwas <- length(which((tf_data[,i] <=d) & (tf_data$GWAS_CAD_tf == 1)))
  high_diff_notGwas <- length(which((tf_data[,i] >d) & (tf_data$GWAS_CAD_tf == 0)))
  low_diff_notGwas <- length(which((tf_data[,i] <=d) & (tf_data$GWAS_CAD_tf == 0)))
  contingency_table <- matrix(c(high_diff_gwas,low_diff_gwas,high_diff_notGwas,low_diff_notGwas), nrow = 2,dimnames = list(Diff = c("High", "Low"),GWAS = c("yes", "no")))
  test <- fisher.test(contingency_table, alternative = "greater")
  return(as.numeric(test$p.value))
})
names(CAD_enrich) <- colnames(tf_data)[individuals]

cad_enriched_indiv <- names(which(CAD_enrich < 0.05))
cad_enriched_indiv
cad_df <- as.data.frame(CAD_enrich)
colnames(cad_df) <- "pvalue"
cad_df$Tissue <- NA
cad_df$Tissue[1:119] <- "LCL"
cad_df$Tissue[120:238] <- "iPSC"
cad_df$Tissue[239:357] <- "iPSC-CM"
cad_df$Individual <- NA
cad_df$Individual <- c(c(1:119),c(1:119),c(1:119))

#pdf("banovich_CAD_enrichment.pdf",width = 5, height = 3.5)
ggplot(cad_df) + geom_point(shape = 19, aes(x = reorder(Individual, log10(pvalue)), y = -log10(pvalue), col = Tissue),) + theme_classic()+ scale_color_manual(values=pallet) + geom_abline(slope = 0, intercept = -log10(0.05), linetype = "dashed", col = "black") + xlab("Individual") + theme( axis.text.x=element_blank(), axis.ticks.x=element_blank())  + labs(y = "-log10(p-value)", title = "Enrichment of disrupted TFs in CAD genes",color = "Cell type") + annotate("text", x = 110, y = 1.4, label = "p = 0.05")
#dev.off()

```


CAD
```{r}
cad_tfs <- tf_degrees_scaled2[which(tf_degrees_scaled2$GWAS_CAD_tf == 1),1]
tf_data <- tf_degrees_scaled2
individuals <- c(2:358)
CAD_enrich <- sapply(individuals, FUN = function(i){
  mylist <- as.vector(tf_degrees_scaled2[order(-as.numeric(as.vector(tf_degrees_scaled2[,i]))),c(1)])
  test <- TestNodeRank(mylist, cad_tfs)
  return(test[3])
})
names(CAD_enrich) <- colnames(tf_data)[individuals]

cad_enriched_indiv <- names(which(CAD_enrich < 0.05))
cad_enriched_indiv
cad_df <- as.data.frame(CAD_enrich)
colnames(cad_df) <- "pvalue"
cad_df$Tissue <- NA
cad_df$Tissue[1:119] <- "LCL"
cad_df$Tissue[120:238] <- "iPSC"
cad_df$Tissue[239:357] <- "iPSC-CM"
cad_df$Individual <- NA
cad_df$Individual <- c(c(1:119),c(1:119),c(1:119))

#pdf("banovich_CAD_enrichment.pdf",width = 5, height = 3.5)
ggplot(cad_df) + geom_point(shape = 19, aes(x = reorder(Individual, log10(pvalue)), y = -log10(pvalue), col = Tissue),) + theme_classic()+ scale_color_manual(values=pallet) + geom_abline(slope = 0, intercept = -log10(0.05), linetype = "dashed", col = "black") + xlab("Individual") + theme( axis.text.x=element_blank(), axis.ticks.x=element_blank())  + labs(y = "-log10(p-value)", title = "Enrichment of disrupted TFs in CAD genes",color = "Cell type") + annotate("text", x = 110, y = 1.4, label = "p = 0.05")
#dev.off()

```


CD
```{r}
cd_tfs <- tf_degrees_scaled2[which((tf_degrees_scaled2$GWAS_CD_tf == 1) &(tf_degrees_scaled2$GWAS_CAD_tf == 0)),1]
tf_data <- tf_degrees_scaled2
individuals <- c(2:358)
CD_enrich <- sapply(individuals, FUN = function(i){
  mylist <- as.vector(tf_degrees_scaled2[order(-as.numeric(as.vector(tf_degrees_scaled2[,i]))),c(1)])
  test <- TestNodeRank(mylist, cd_tfs)
  return(test[3])
})
names(CD_enrich) <- colnames(tf_data)[individuals]

cd_enriched_indiv <- names(which(CD_enrich < 0.05))
cd_enriched_indiv
cd_df <- as.data.frame(CD_enrich)
colnames(cd_df) <- "pvalue"
cd_df$Tissue <- NA
cd_df$Tissue[1:119] <- "LCL"
cd_df$Tissue[120:238] <- "iPSC"
cd_df$Tissue[239:357] <- "iPSC-CM"
cd_df$Individual <- NA
cd_df$Individual <- c(c(1:119),c(1:119),c(1:119))

#pdf("banovich_CAD_enrichment.pdf",width = 5, height = 3.5)
ggplot(cd_df) + geom_point(shape = 19, aes(x = reorder(Individual, log10(pvalue)), y = -log10(pvalue), col = Tissue),) + theme_classic()+ scale_color_manual(values=pallet) + geom_abline(slope = 0, intercept = -log10(0.05), linetype = "dashed", col = "black") + xlab("Individual") + theme( axis.text.x=element_blank(), axis.ticks.x=element_blank())  + labs(y = "-log10(p-value)", title = "Enrichment of disrupted TFs in CD genes",color = "Cell type") + annotate("text", x = 110, y = 1.4, label = "p = 0.05")
#dev.off()

```


CD
```{r}
tf_data <- tf_degrees_scaled2
d = 
individuals <- c(2:358)
CD_enrich <- sapply(individuals, FUN = function(i){
  high_diff_gwas <- length(which((tf_data[,i] >d) & (tf_data$GWAS_CD_tf == 1)))
  low_diff_gwas <- length(which((tf_data[,i] <=d) & (tf_data$GWAS_CD_tf == 1)))
  high_diff_notGwas <- length(which((tf_data[,i] >d) & (tf_data$GWAS_CD_tf == 0)))
  low_diff_notGwas <- length(which((tf_data[,i] <=d) & (tf_data$GWAS_CD_tf == 0)))
  contingency_table <- matrix(c(high_diff_gwas,low_diff_gwas,high_diff_notGwas,low_diff_notGwas), nrow = 2,dimnames = list(Diff = c("High", "Low"),GWAS = c("yes", "no")))
  test <- fisher.test(contingency_table, alternative = "greater")
  return(as.numeric(test$p.value))
})
names(CD_enrich) <- colnames(tf_data)[individuals]
cd_enriched_indiv <- names(which(CD_enrich < 0.05))
cd_enriched_indiv

cd_df <- as.data.frame(CD_enrich)
colnames(cd_df) <- "pvalue"
cd_df$Tissue <- NA
cd_df$Tissue[1:119] <- "LCL"
cd_df$Tissue[120:238] <- "iPSC"
cd_df$Tissue[239:357] <- "iPSC-CM"
cd_df$Individual <- NA
cd_df$Individual <- c(c(1:119),c(1:119),c(1:119))

#pdf("banovich_CD_enrichment.pdf",width = 5, height = 3.5)
ggplot(cd_df) + geom_point(shape = 19, aes(x = reorder(Individual, log10(pvalue)), y = -log10(pvalue), col = Tissue),) + theme_classic()+ scale_color_manual(values=pallet) + geom_abline(slope = 0, intercept = -log10(0.05), linetype = "dashed", col = "black") + xlab("Individual") + theme( axis.text.x=element_blank(), axis.ticks.x=element_blank()) + labs(y = "-log10(p-value)", title = "Enrichment of disrupted TFs (d > 15) in CD genes",color = "Cell type") + annotate("text", x = 110, y = 1.4, label = "p = 0.05")

#dev.off()
```





# Some t tests and box plots
```{r}
tf_degrees <- tf_degrees_hard_thresh_scaled
tf_degree_lcl <- melt(tf_degrees[,c(1,c(2:120))], id.vars = c("tf"))
tf_degree_lcl$tissue <- "LCL"
tf_degree_iPSC <- melt(tf_degrees[,c(1,c(121:239))], id.vars = c("tf"))
tf_degree_iPSC$tissue <- "iPSC"
tf_degree_iPSC_CM <- melt(tf_degrees[,c(1,c(240:358))], id.vars = c("tf"))
tf_degree_iPSC_CM$tissue <- "iPSC-CM"
tf_degrees_melted <- rbind(tf_degree_lcl,tf_degree_iPSC,tf_degree_iPSC_CM)
colnames(tf_degrees_melted) <- c("tf","individual","diff_out_degree","Tissue")

ggplot(tf_degrees_melted, aes(x=Tissue, y=diff_out_degree, fill=Tissue, col = Tissue)) + geom_violin() + theme_bw() + scale_fill_manual(values=pallet) + scale_color_manual(values=pallet) + labs(title="Distribution of TF Disruption Scores", x ="Cell type", y = "TF Disruption Score") + theme(legend.position="none")

ggplot(tf_degrees_melted, aes(x=diff_out_degree,  color=Tissue)) + geom_density() + theme_bw() + scale_color_manual(values=pallet) +labs(title=NULL, x ="Scaled TF disruption score", y = "Frequency") +  xlim(-0.5,0.5)

ggplot(tf_degrees_melted, aes(x=diff_out_degree,  color=Tissue)) + geom_density() + theme_bw() + scale_color_manual(values=pallet) +labs(title=NULL, x ="Scaled TF disruption score", y = "Frequency") +  xlim(-1,1)

ggplot(tf_degrees_melted, aes(x=diff_out_degree,  color=Tissue)) + geom_density() + theme_bw() + scale_color_manual(values=pallet) +labs(title=NULL, x ="Scaled TF disruption score", y = "Frequency") +  xlim(1,10)

ggplot(tf_degrees_melted, aes(x=diff_out_degree,  color=Tissue)) + geom_density() + theme_bw() + scale_color_manual(values=pallet) +labs(title=NULL, x ="Scaled TF disruption score", y = "Frequency") +  xlim(5,20)

ggplot(tf_degrees_melted, aes(x=diff_out_degree,  color=Tissue)) + geom_density() + theme_bw() + scale_color_manual(values=pallet) +labs(title=NULL, x ="Scaled TF disruption score", y = "Frequency") +  xlim(1,30)
```

```{r}
tf_degrees <- tf_degrees_scaled2
colnames(tf_degree_iPSC_CM) <-  c("tf","individual","diff_out_degree","tissue")
tf_degree_iPSC_CM$CAD <- tf_degrees$GWAS_CAD_tf[match(tf_degree_iPSC_CM$tf, tf_degrees$tf)]

test_cad_in_cm <- t.test(tf_degree_iPSC_CM[which(tf_degree_iPSC_CM$CAD == 1),]$diff_out_degree,tf_degree_iPSC_CM[which(tf_degree_iPSC_CM$CAD == 0),]$diff_out_degree, alternative="greater")

mean0 <- mean(tf_degree_iPSC_CM[which(tf_degree_iPSC_CM$CAD == 0),]$diff_out_degree)
mean1 <- mean(tf_degree_iPSC_CM[which(tf_degree_iPSC_CM$CAD == 1),]$diff_out_degree)

p1 <- ggplot(tf_degree_iPSC_CM, aes(x = as.factor(CAD), y = diff_out_degree, group = as.factor(CAD), fill = as.factor(CAD))) + scale_fill_manual(values = pallet) + geom_violin() + theme_bw() + geom_point(x = as.factor(0), y = mean0, shape=18,size=5, color="#E41A1C")+ geom_point(x = as.factor(1), y = mean1, shape=18,size=5, color="#E41A1C") + labs(title = "Distribution of disruption scores for CAD and non-CAD TFs in iPSC-CMs",y = "TF disruption score", x = "CAD TF?") + theme(legend.position = "none")

p2 <- ggplot(tf_degree_iPSC_CM, aes(x = as.factor(CAD), y = diff_out_degree, group = as.factor(CAD), fill = as.factor(CAD))) + scale_fill_manual(values = pallet) + geom_violin() + theme_bw() + geom_point(x = as.factor(0), y = mean0, shape=18,size=5, color="#E41A1C")+ geom_point(x = as.factor(1), y = mean1, shape=18,size=5, color="#E41A1C")+ ylim(-1,1) + labs(title = "Distribution of disruption scores for CAD and non-CAD TFs in iPSC-CMs",y = "TF disruption score", x = "CAD TF?") + theme(legend.position = "none")

p3 <- grid.arrange(p1 + theme(legend.position="none"), p2 + theme(legend.position="none"), nrow=1, widths = c(3,3))
pdf("cad_1_0_ipsc_cm.pdf",width = 6, height = 3)
plot(p3)
dev.off()

ggplot(tf_degree_iPSC_CM, aes(x = as.factor(CAD), y = diff_out_degree,group = as.factor(CAD))) + geom_jitter(position=position_jitter(0.2), size = 0.1) + theme_bw() + ylim(-1,1) + geom_point(aes(x = as.factor(0), y = mean0), shape=18,size=5, color="#E41A1C")+ geom_point(x = as.factor(1), y = mean1, shape=18,size=5, color="#E41A1C")


colnames(tf_degree_iPSC_CM) <-  c("tf","individual","diff_out_degree","tissue")
tf_degree_iPSC_CM$CD <- tf_degrees_scaled2$GWAS_CD_tf[match(tf_degree_iPSC_CM$tf, tf_degrees_scaled2$tf)]

test_cd_in_cm <- t.test(tf_degree_iPSC_CM[which(tf_degree_iPSC_CM$CD == 1),]$diff_out_degree,tf_degree_iPSC_CM[which(tf_degree_iPSC_CM$CD == 0),]$diff_out_degree, alternative="greater")

colnames(tf_degree_lcl) <-  c("tf","individual","diff_out_degree","tissue")
tf_degree_lcl$CD <- tf_degrees_scaled2$GWAS_CD_tf[match(tf_degree_lcl$tf, tf_degrees_scaled2$tf)]

test_cd_in_lcl <- t.test(tf_degree_lcl[which(tf_degree_lcl$CD == 1),]$diff_out_degree,tf_degree_lcl[which(tf_degree_lcl$CD == 0),]$diff_out_degree, alternative="greater")

colnames(tf_degree_lcl) <-  c("tf","individual","diff_out_degree","tissue")
tf_degree_lcl$CAD <- tf_degrees_scaled2$GWAS_CAD_tf[match(tf_degree_lcl$tf, tf_degrees_scaled2$tf)]

test_cad_in_lcl <- t.test(tf_degree_lcl[which(tf_degree_lcl$CAD == 1),]$diff_out_degree,tf_degree_lcl[which(tf_degree_lcl$CAD == 0),]$diff_out_degree, alternative="greater")

test_cad_in_lcl$p.value
test_cad_in_cm$p.value
test_cd_in_lcl$p.value
test_cd_in_cm$p.value
```

# Some basic-ass plots

```{r}
cad_tfs_degree_hard_thresh <- tf_degrees_hard_thresh_scaled[which(tf_degrees_hard_thresh_scaled$GWAS_CAD_tf == 1),c(1:358)]
cad_tfs_degree_hard_thresh_melted <- melt(cad_tfs_degree_hard_thresh)
colnames(cad_tfs_degree_hard_thresh_melted) <- c("tf","sample","tf_diff_degree")
cad_tfs_degree_hard_thresh_melted <- separate(cad_tfs_degree_hard_thresh_melted, sample, c("cellType","tag", "indiv"), "_", remove = TRUE)

ggplot(cad_tfs_degree_hard_thresh_melted) + geom_point(shape = 19, aes(x = reorder(indiv, -tf_diff_degree), y = tf_diff_degree, col = cellType),) + theme_classic()+ scale_color_manual(values=pallet)+ xlab("Individual") #+ theme( axis.text.x=element_blank(), axis.ticks.x=element_blank())  + labs(y = "-log10(p-value)", title = "Enrichment of disrupted TFs in CAD genes",color = "Cell type") + annotate("text", x = 110, y = 1.4, label = "p = 0.05")
#dev.off()

```



```{r}
cd_tfs_degree_hard_thresh <- tf_degrees_hard_thresh_scaled[which(tf_degrees_hard_thresh_scaled$GWAS_MI_tf == 1),c(1:358)]
cd_tfs_degree_hard_thresh_melted <- melt(cd_tfs_degree_hard_thresh)
colnames(cd_tfs_degree_hard_thresh_melted) <- c("tf","sample","tf_diff_degree")
cd_tfs_degree_hard_thresh_melted <- separate(cd_tfs_degree_hard_thresh_melted, sample, c("cellType","tag", "indiv"), "_", remove = TRUE)

ggplot(cd_tfs_degree_hard_thresh_melted) + geom_point(shape = 19, aes(x = reorder(indiv, -tf_diff_degree), y = tf_diff_degree, col = cellType),) + theme_classic()+ scale_color_manual(values=pallet)+ xlab("Individual") #+ theme( axis.text.x=element_blank(), axis.ticks.x=element_blank())  + labs(y = "-log10(p-value)", title = "Enrichment of disrupted TFs in CAD genes",color = "Cell type") + annotate("text", x = 110, y = 1.4, label = "p = 0.05")
#dev.off()

```

```{r}
disease_test_tfs_degree_hard_thresh <- tf_degrees_hard_thresh_scaled[which(tf_degrees_hard_thresh_scaled$GWAS_CD   == 1),c(1:358)]
disease_test_tfs_degree_hard_thresh_melted <- melt(disease_test_tfs_degree_hard_thresh)
colnames(disease_test_tfs_degree_hard_thresh_melted) <- c("tf","sample","tf_diff_degree")
disease_test_tfs_degree_hard_thresh_melted <- separate(disease_test_tfs_degree_hard_thresh_melted, sample, c("cellType","tag", "indiv"), "_", remove = TRUE)

ggplot(disease_test_tfs_degree_hard_thresh_melted) + geom_point(shape = 19, aes(x = reorder(indiv, -tf_diff_degree), y = tf_diff_degree, col = cellType),) + theme_classic()+ scale_color_manual(values=pallet)+ xlab("Individual") #+ theme( axis.text.x=element_blank(), axis.ticks.x=element_blank())  + labs(y = "-log10(p-value)", title = "Enrichment of disrupted TFs in CAD genes",color = "Cell type") + annotate("text", x = 110, y = 1.4, label = "p = 0.05")
#dev.off()

```

```{r}
disease_test_gene_degree_hard_thresh1 <- gene_degrees_hard_thresh_scaled[which(gene_degrees_hard_thresh_scaled$GWAS_BMI_gene== 1),c(1:358)]
disease_test_degree_hard_threshmelt1 <- melt(disease_test_gene_degree_hard_thresh1)
colnames(disease_test_degree_hard_threshmelt1) <- c("gene","sample","tf_diff_degree")
disease_test_degree_hard_threshmelt1 <- separate(disease_test_degree_hard_threshmelt1, sample, c("cellType","tag", "indiv"), "_", remove = TRUE)

ggplot(disease_test_degree_hard_threshmelt1) + geom_point(shape = 19, aes(x = reorder(indiv, -tf_diff_degree), y = tf_diff_degree, col = cellType),) + theme_classic()+ scale_color_manual(values=pallet)+ xlab("Individual") #+ theme( axis.text.x=element_blank(), axis.ticks.x=element_blank())  + labs(y = "-log10(p-value)", title = "Enrichment of disrupted TFs in CAD genes",color = "Cell type") + annotate("text", x = 110, y = 1.4, label = "p = 0.05")
#dev.off()


```



```{r}
gene_degrees <- gene_degrees_hard_thresh_scaled
gene_degree_lcl <- melt(gene_degrees[,c(1,c(2:120))], id.vars = c("gene"))
gene_degree_lcl$tissue <- "LCL"
gene_degree_iPSC <- melt(gene_degrees[,c(1,c(121:239))], id.vars = c("gene"))
gene_degree_iPSC$tissue <- "iPSC"
gene_degree_iPSC_CM <- melt(gene_degrees[,c(1,c(240:358))], id.vars = c("gene"))
gene_degree_iPSC_CM$tissue <- "iPSC-CM"
gene_degrees_melted <- rbind(gene_degree_lcl,gene_degree_iPSC,gene_degree_iPSC_CM)
colnames(gene_degrees_melted) <- c("gene","individual","diff_out_degree","Tissue")

ggplot(gene_degrees_melted, aes(x=Tissue, y=diff_out_degree, fill=Tissue, col = Tissue)) + geom_violin() + theme_bw() + scale_fill_manual(values=pallet) + scale_color_manual(values=pallet) + labs(title="Distribution of gene Disruption Scores", x ="Cell type", y = "gene Disruption Score") + theme(legend.position="none")

ggplot(gene_degrees_melted, aes(x=diff_out_degree,col = Tissue, fill=Tissue, group = Tissue)) + geom_density(alpha = 0.1, adjust = 0.25) + theme_bw() + scale_fill_manual(values=pallet) + scale_color_manual(values=pallet) +labs(title=NULL, x ="Scaled gene disruption score", y = "Frequency")

ggplot(gene_degrees_melted, aes(x=diff_out_degree,col = Tissue, fill=Tissue, group = Tissue)) + geom_density(alpha = 0.1, adjust = 0.5) + theme_bw() + scale_fill_manual(values=pallet) + scale_color_manual(values=pallet) +labs(title=NULL, x ="Scaled gene disruption score", y = "Frequency") +  xlim(0.1, 50)

```