---
title: "Final EGRET v1: testing alpaca on a banovich network"
author: "Deborah Weighill"
date: "July 29, 2020"
output:
  html_notebook:
    toc: true
    theme: cosmo
    df_print: paged
---


# Overview
This script validates the PANDA and EGRET networks against ChIP-seq data.


# Libraries, tags and inputs
Load libraries, set tag

```{r}
library(rtracklayer)
library(tidyr)
library(pROC)
library(reshape)
library(PRROC)
library(dplyr)
library(precrec)
library(ggplot2)
library(Matrix)
library(igraph)
library(GOstats)
library("org.Hs.eg.db")
library(condor)
library(GO.db)
library(ALPACA)

```
`
```{r}

load("../outputs/iPSC-CM_table_banovich_finalEgret_v1_allModels_smart1_07042020.RData")
```

```{r}

#individuals <- c(1:119)
individuals <- c(101,105,109,111,115,119,39,49,59,69,79,89,99,91,81,71)
mclapply(individuals, function(i) {
  egret_col <- 4 + i
  panda_col <- 4
  out <- paste0("/home/ubuntu/EGRET/final_egret_v1_banovich/alpaca/iPSC-CM_",i)
  alpaca <- alpaca(regnet_edge_table_iPSC_CM[,c(2,3,panda_col,egret_col)], out, verbose = T)

}, mc.cores = 7,mc.preschedule=TRUE)
```


