---
title: "Playing with QBiC"
author: "Deborah Weighill"
date: "June 30, 2020"
output:
  html_notebook:
    toc: true
    theme: cosmo
    df_print: paged
---

```{r}
qbic <- read.table("../genotype_data/QTLs_GM12878_K562_QbicPred_finalEGRET_v1_06172020.txt", header = TRUE)
qbic <- separate(qbic, pbmname, c("species", "array","source","something"), "\\|", remove = TRUE)
ggplot(qbic, aes(x = species, y = p_value, group = species, color = species)) + geom_boxplot() + theme(legend.position = "none",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
range(as.numeric(qbic$p_value)) 

remove <- c("bound>bound","unbound>unbound","ambiguous>ambiguous")
qbic_changing <- qbic[which(!(qbic$binding_status %in% remove)),]

qbic_changing_neg <- qbic_changing[which(qbic_changing$diff < 0),]

p <- ggplot(qbic_changing, aes(x = species, y = p_value, group = species, color = species)) + geom_boxplot() + theme(legend.position = "none",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
pdf("qbic_pvals_diffs.pdf",width = 9, height = 9)
plot(p)
dev.off()

average_pvals <- aggregate(qbic_changing$p_value, by = list(qbic_changing$species), FUN=mean)

qbic_changing_human <- qbic_changing[which((qbic_changing$species == "Homo_sapiens") & (qbic_changing$diff < 0)),]
qbic_changing_others_highconf <- qbic_changing[which((qbic_changing$p_value < 10^-20) & (qbic_changing$diff < 0)),]


p <- ggplot(qbic_changing_neg, aes(x = species, y = p_value, group = species, color = species)) + geom_boxplot() + theme(legend.position = "none",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
pdf("qbic_pvals_diffs.pdf",width = 9, height = 3)
```

```{r}
library(jcolors)
library(RColorBrewer)
# Define the number of colors you want
nb.cols <- 58
mycolors <- colorRampPalette(jcolors("pal2"))(nb.cols)

qbic_neg <- qbic[which(qbic$diff < 0),]
qbic_diff <- qbic_neg[which(!(qbic_neg$binding_status %in% remove)),]

p <- ggplot(qbic_neg, aes(x = species, y = p_value, group = species, color = species)) + geom_boxplot() + theme(legend.position = "none",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
plot(p)

p2 <- ggplot(qbic_diff, aes(x = species, y = p_value, group = species, color = species)) + geom_boxplot() + theme(legend.position = "none",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
plot(p2)

p3 <- ggplot(qbic_diff, aes(x = species, y = -log10(p_value), group = species, color = species)) + geom_boxplot() + theme(legend.position = "none",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = mycolors)
plot(p3)
```


```{r}
nb.cols <- 58
mycolors <- colorRampPalette(jcolors("pal5"))(nb.cols)
p3 <- ggplot(qbic_diff, aes(x = species, y = -log10(p_value), group = species, color = species)) + geom_boxplot()  + scale_color_manual(values = mycolors)+theme_bw()+ theme(legend.position = "none",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+labs(title="QBiC prediction significance by PBM model species", x ="PBM species", y = "-log10(p value)")
pdf("qbic_pvals_diffs.pdf",width = 9, height = 5)
plot(p3)
dev.off()
```


```{r}
library(jcolors)
library(RColorBrewer)
# Define the number of colors you want
nb.cols <- 58
mycolors <- colorRampPalette(jcolors("pal2"))(nb.cols)


remove <- c("bound>bound","unbound>unbound","ambiguous>ambiguous","ambiguous>bound","unbound>ambiguous","unbound>bound")
qbic_diff <- qbic[which(!(qbic$binding_status %in% remove)),]

p <- ggplot(qbic_neg, aes(x = species, y = p_value, group = species, color = species)) + geom_boxplot() + theme(legend.position = "none",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
plot(p)

p2 <- ggplot(qbic_diff, aes(x = species, y = p_value, group = species, color = species)) + geom_boxplot() + theme(legend.position = "none",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
plot(p2)

p3 <- ggplot(qbic_diff, aes(x = species, y = -log10(p_value), group = species, color = species)) + geom_boxplot() + theme(legend.position = "none",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = mycolors)
plot(p3)
```









